name: itrie
description: >
  Efficient, immutable and stack safe implementation of a Trie data structure in dart: autocomplete, text search, spell checking, strings and prefixes.
version: 0.0.2
homepage: https://www.sandromaglione.com/
repository: https://github.com/SandroMaglione/itrie
author: Maglione Sandro <lass.maglio@gmail.com>
issue_tracker: https://github.com/SandroMaglione/itrie/issues

environment:
  sdk: ^3.2.3

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
