name: itrie
description: >
  Efficient, immutable and stack safe implementation of a `Trie` data structure in dart.
  Ideal for autocomplete, text search, spell checking, and generally when working with string and prefixes.
version: 0.0.1
homepage: https://www.sandromaglione.com/
repository: https://github.com/SandroMaglione/itrie
author: Maglione Sandro <lass.maglio@gmail.com>
issue_tracker: https://github.com/SandroMaglione/itrie/issues

environment:
  sdk: ^3.2.3

dependencies:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
